#!/bin/bash
# Post-create setup for GePT Codespace
# Runs once after the container is built.
set -e

echo "=========================================="
echo "  GePT Codespace Setup"
echo "=========================================="
echo ""

# ── 1. SSH Key Setup ──────────────────────────
echo "→ Configuring SSH key for Ampere tunnel..."
mkdir -p ~/.ssh
if [ -n "$SSH_DEPLOY_KEY" ]; then
    echo "$SSH_DEPLOY_KEY" > ~/.ssh/ampere_key
    chmod 600 ~/.ssh/ampere_key
    ssh-keyscan -H 150.136.170.128 >> ~/.ssh/known_hosts 2>/dev/null
    echo "  ✓ SSH key configured"
else
    echo "  ✗ SSH_DEPLOY_KEY secret not set — tunnel will not work"
    echo "    Set it in GitHub → repo settings → Secrets → Codespaces"
fi

# ── 2. SSH Tunnel ─────────────────────────────
echo ""
echo "→ Starting SSH tunnel to Ampere PostgreSQL..."
if [ -f ~/.ssh/ampere_key ]; then
    ssh -i ~/.ssh/ampere_key \
        -L 5432:localhost:5432 \
        -o ServerAliveInterval=60 \
        -o ServerAliveCountMax=3 \
        -o StrictHostKeyChecking=no \
        -N -f ubuntu@150.136.170.128

    sleep 2
    if pgrep -f "ssh.*5432:localhost:5432" > /dev/null; then
        echo "  ✓ SSH tunnel running (localhost:5432 → Ampere)"
    else
        echo "  ✗ SSH tunnel failed to start"
    fi
else
    echo "  ⊘ Skipped (no SSH key)"
fi

# ── 3. Python Dependencies ───────────────────
echo ""
echo "→ Installing Python dependencies (engine)..."
cd /workspaces/gept/packages/engine
python3 -m venv .venv
.venv/bin/pip install --upgrade pip --quiet
.venv/bin/pip install -r requirements.txt --quiet
echo "  ✓ Engine venv ready at packages/engine/.venv"

# ── 4. Node Dependencies ─────────────────────
echo ""
echo "→ Installing Node dependencies (web)..."
cd /workspaces/gept/packages/web
npm install --silent 2>/dev/null
echo "  ✓ Web node_modules ready"

# ── 5. Generate .env Files ───────────────────
echo ""
echo "→ Generating .env files from Codespace secrets..."

# Engine .env
cat > /workspaces/gept/packages/engine/.env << ENVEOF
# Generated by Codespace setup — do not commit
DB_CONNECTION_STRING=${DB_CONNECTION_STRING:-postgresql://localhost:5432/osrs_data}
REDIS_URL=redis://localhost:6379
API_HOST=0.0.0.0
API_PORT=8000
CORS_ORIGINS=https://${CODESPACE_NAME}-4321.app.github.dev,http://localhost:4321
LOG_FORMAT=text
LOG_LEVEL=INFO
INTERNAL_API_KEY=${INTERNAL_API_KEY:-}
WEBHOOK_SECRET=${WEBHOOK_SECRET:-}
ENVEOF
echo "  ✓ packages/engine/.env"

# Web .env.local
cat > /workspaces/gept/packages/web/.env.local << ENVEOF
# Generated by Codespace setup — do not commit
DATABASE_URL=${NEON_DATABASE_URL:-}
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-dev-secret-change-me-in-codespace-secrets}
BETTER_AUTH_URL=https://${CODESPACE_NAME}-4321.app.github.dev
PUBLIC_APP_URL=https://${CODESPACE_NAME}-4321.app.github.dev
SITE=https://${CODESPACE_NAME}-4321.app.github.dev
PREDICTION_API=http://localhost:8000
PREDICTION_API_KEY=${INTERNAL_API_KEY:-}
WEBHOOK_SECRET=${WEBHOOK_SECRET:-}
ENVEOF
echo "  ✓ packages/web/.env.local"

# ── 6. Verify Connections ────────────────────
echo ""
echo "→ Verifying connections..."

# PostgreSQL via tunnel
if [ -n "$DB_CONNECTION_STRING" ]; then
    if psql "$DB_CONNECTION_STRING" -c "SELECT 1" > /dev/null 2>&1; then
        echo "  ✓ Ampere PostgreSQL (via tunnel)"
    else
        echo "  ✗ Ampere PostgreSQL — check tunnel and DB_CONNECTION_STRING"
    fi
else
    echo "  ⊘ Ampere PostgreSQL (DB_CONNECTION_STRING not set)"
fi

# Redis
if redis-cli ping > /dev/null 2>&1; then
    echo "  ✓ Redis"
else
    echo "  ✗ Redis — container may still be starting"
fi

# ── Done ─────────────────────────────────────
echo ""
echo "=========================================="
echo "  Setup complete!"
echo "=========================================="
echo ""
echo "  Start the engine:"
echo "    cd packages/engine && source .venv/bin/activate"
echo "    uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload"
echo ""
echo "  Start the web frontend:"
echo "    cd packages/web && npm run dev"
echo ""
echo "  Then open the forwarded port 4321 in your browser."
echo "=========================================="
